name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

defaults:
  run:
    working-directory: Anaire.30ppm-50ppm/anaire-device.NodeMCULuaAmicaV2
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Set up Platformio
        run: pip install -U platformio
          platformio update

      - name: Pull build deps
        run:  git submodule update --init --recursive

      - name: Build firmware
        run: platformio run

      - name: create build tag
        run: echo "BUILD_TAG=.pio/build/huzzah/firmware_$(git rev-parse --short HEAD).bin" >> $GITHUB_ENV

      - uses: actions/upload-artifact@v2
        name: Upload firmware files
        with:
          name: ${{ env.BUILD_TAG }}
          path: |
            ${{ env.BINARY }}
            ${{ env.ELF }}
