name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

defaults:
  run:
    working-directory: Anaire.30ppm-50ppm/anaire-device.NodeMCULuaAmicaV2
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Set up Platformio
        run: pip install -U platformio
          platformio update

      - name: Pull build deps
        run:  |
          cd Anaire.30ppm-50ppm/anaire-device.NodeMCULuaAmicaV2
          git submodule update --init --recursive

      - name: Build firmware
        run: platformio run

      - name: Check if firmware files exits
        run: |
          echo "BINARY=$(find . -type f -name "*.bin")" >> $GITHUB_ENV
          echo "ELF=$(find . -type f -name "*.elf")" >> $GITHUB_ENV

      - name: create build tag (1/2)
        run: echo "TEMP_TAG=${BINARY##*/}" >> $GITHUB_ENV
      - name: create build tag (2/2)
        run: echo "BUILD_TAG=$(echo ${TEMP_TAG%.*})" >> $GITHUB_ENV

      - uses: actions/upload-artifact@v2
        name: Upload firmware files
        with:
          name: ${{ env.BUILD_TAG }}
          path: |
            ${{ env.BINARY }}
            ${{ env.ELF }}
